plugins = []
functionsDirectory = "/root/.openclaw/workspace/snarkyalma/netlify/functions"
functionsDirectoryOrigin = "config-v1"
headers = []
redirects = []

[functions]

[functions."*"]
node_bundler = "esbuild"

[build]
publish = "/root/.openclaw/workspace/snarkyalma"
publishOrigin = "default"
base = "/root/.openclaw/workspace/snarkyalma"
functions = "/root/.openclaw/workspace/snarkyalma/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]